resource_group_name = "rg-terraform-prod"
location = "West-Europe"
app_service_plan_name_backend = "azapp-terraform-prod"
app_service_name_backend = "azapp-terraform-prod"
application_insights_name = "appi-terraform-prod"
